---
title: "main.Rmd"
author: "Timo Grossenbacher"
date: "April 9, 2016"
output: html_document
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}

setwd("/home/tgrossen/SRF/klumpenrisiko/preprocessing")

knitr::opts_chunk$set(fig.width=12, fig.height=8,  warning=FALSE, message=FALSE)

options(scipen = 10)
# load necessary packages
if(!require(dplyr)) {
  install.packages("dplyr", repos="http://cran.us.r-project.org")
  require(dplyr)
}
if(!require(tidyr)) {
  install.packages("tidyr", repos="http://cran.us.r-project.org")
  require(tidyr)
}
if(!require(ggplot2)) {
  install.packages("ggplot2", repos="http://cran.us.r-project.org")
  require(ggplot2)
}
if(!require(magrittr)) {
  install.packages("magrittr", repos="http://cran.us.r-project.org")
  require(magrittr)
}
if(!require(googlesheets)) {
  install.packages("googlesheets", repos="http://cran.us.r-project.org")
  require(googlesheets)
}
if(!require(stringr)) {
  install.packages("stringr", repos="http://cran.us.r-project.org")
  require(stringr)
}
if(!require(httr)) {
  install.packages("httr", repos="http://cran.us.r-project.org")
  require(httr)
}
# if(!require(jsonlite)) {
#   install.packages("jsonlite", repos="http://cran.us.r-project.org")
#   require(jsonlite)
# }
# if(!require(RSQLite)) {
#   install.packages("RSQLite", repos="http://cran.us.r-project.org")
#   require(RSQLite)
# }
# 
# if(!require(lazyeval)) {
#   install.packages("lazyeval", repos="http://cran.us.r-project.org")
#   require(lazyeval)
# }
# 
# if(!require(stringdist)) {
#   install.packages("stringdist", repos="http://cran.us.r-project.org")
#   require(stringdist)
# }
library(scales)
```

```{r}

source_sheet <- gs_key("1Ua-hgSpfA4G4WiVEZW7rt39qM0cM2W3G5bAXTdSy6qs")

id_map_url <- "https://docs.google.com/spreadsheets/d/1Ua-hgSpfA4G4WiVEZW7rt39qM0cM2W3G5bAXTdSy6qs/pubhtml"

source_kw <- id_map_url %>%
  googlesheets::gs_url() %>%
#   googlesheets::gs_read(ws = "KW", range = cell_limits(c(1,NA), c(1,6)))
    googlesheets::gs_read_listfeed(ws = "KW")

source_kw_betreiber <- id_map_url %>%
  googlesheets::gs_url() %>%
  googlesheets::gs_read_listfeed(ws = "KW_Betreiber")

source_kw_betreiber_shareholder <- id_map_url %>%
  googlesheets::gs_url() %>%
  googlesheets::gs_read_listfeed(ws = "KW_Betreiber_Shareholder")

source_shareholder_shareholder <- id_map_url %>%
  googlesheets::gs_url() %>%
  googlesheets::gs_read_listfeed(ws = "Shareholder_Shareholder")

not_unique_shareholders <- c(source_kw_betreiber_shareholder$name, source_shareholder_shareholder$fkkwshakeholderownedid, source_shareholder_shareholder$nameownerid)

frequencies <- as.data.frame(table(not_unique_shareholders))

# create final shareholder table
shareholders <- data.frame(id = 1:length(unique(not_unique_shareholders)), name = unique(not_unique_shareholders), form = rep(NA, length(unique(not_unique_shareholders))), power_output = rep(0, length(unique(not_unique_shareholders))))

# add form
source_kw_betreiber_shareholder %<>% distinct(rechtsform, name)
shareholders %<>% 
    left_join(source_kw_betreiber_shareholder, by = c("name")) %>% 
    select(-form, -fkkwbetreiber, -isleaf, -land) %>% 
    rename(form = rechtsform) 

shareholders %<>% mutate(form = ifelse(str_detect(name, "^Gemeinde"), "Gemeinde", form))
shareholders %<>% mutate(form = ifelse(str_detect(name, "^Kanton"), "Kanton", form))
shareholders %<>% mutate(form = ifelse(str_detect(name, "(AG$|SA$|SE$)"), "AG", form))
shareholders %<>% mutate(form = ifelse(str_detect(name, "(Sarl|GmbH)$"), "GmbH", form))
shareholders %<>% mutate(form = ifelse(str_detect(name, "Staat"), "Staat", form))
shareholders %<>% mutate(form = ifelse(is.na(form), "tbd", form))

shareholders %<>% select(id, name, form, power_output)

# power plants need to be added

kw <- source_kw %>% 
    select(name = zentrale, power_output = leistungmw, form = kwtyp) %>% 
    # they should already be distinct, but lets still reassure
    distinct(name, power_output) %>%  
    mutate(id = (nrow(shareholders)+1):(nrow(shareholders) + nrow(source_kw)))
shareholders <- rbind(shareholders, kw)
# power plant operators need to be added
kw_betreiber <- source_kw_betreiber %>% 
    mutate(power_output = rep(0, nrow(source_kw_betreiber)), form = rep("Kraftwerksbetreiber", nrow(source_kw_betreiber))) %>% 
    distinct(name, form) %>% 
    select(name, power_output, form) %>% 
    mutate(id = (nrow(shareholders)+1):(nrow(shareholders) + length(unique(source_kw_betreiber$name))))

shareholders <- rbind(shareholders, kw_betreiber)

# plausibility check: are IDs still unique?
length(unique(shareholders$id)) == 105

shareholders %>% write.csv("../actor.csv", row.names = F)

# compile shareholder relations
# mapping between kw and kw_betreiber
kw_kw_betreiber_relations <- source_kw %>% 
    left_join(shareholders, by = c("zentrale" = "name")) %>% 
    select(owned_id = id, wastanummer) %>% 
    mutate(share = 1) %>% 
    left_join(source_kw_betreiber, by = c("wastanummer" = "fkwastanummer")) %>% 
    select(owned_id, owner_name = name, share) %>% 
    left_join(shareholders, by = c("owner_name" = "name")) %>% 
    select(owned_id, owner_id = id, share)

# mapping between kw_betreiber and shareholders
# join with shareholders table to get IDs 
tmp <- source_kw_betreiber %>% 
    left_join(shareholders, by = c("name")) %>% 
    select(betreiber_id = id.x, shareholder_id = id.y, shareholder_name = name)
# join with source_kw_betreiber_shareholder
tmp2 <- source_kw_betreiber_shareholder %>% 
    left_join(tmp, by = c("fkkwbetreiber" = "betreiber_id")) %>% 
    select(owned_id = shareholder_id, owner_name = name, isleaf, share = anteilprozent)
# join with shareholders table to get ID
kw_betreiber_shareholder_relations <- tmp2 %>% 
    left_join(shareholders, by = c("owner_name" = "name")) %>% 
    select(owned_id, owner_id = id, share)

# mapping between shareholders and shareholders
shareholder_shareholder_relations <- source_shareholder_shareholder %>%
    left_join(shareholders, by = c("fkkwshakeholderownedid" = "name")) %>% 
    select(owned_id = id, nameownerid, share = anteil) %>% 
    left_join(shareholders, by = c("nameownerid" = "name")) %>% 
    select(owned_id, owner_id = id, share)

# merge
actor_relation <- rbind(kw_kw_betreiber_relations, kw_betreiber_shareholder_relations, shareholder_shareholder_relations)
actor_relation %>% write.csv("../actor_relation.csv", row.names = F)

# rm(source_kw, source_shareholder_shareholder, source_kw_betreiber_shareholder, source_kw_betreiber)
# rm(frequencies, kw_betreiber, kw_kw_betreiber_relations, shareholder_shareholder_relations, shareholder_relation, kw_betreiber_shareholder_relations, kw)
# rm(t, tmp, tmp2, tmp3)
actor <- shareholders
# rm(shareholders)
# plausibility checks
actor_relation %>% 
    group_by(owned_id) %>% 
    summarize(sum_share = sum(share)) %>% 
    # filter(sum_share >= 1.01000 && sum_share <= 0.99000)
    arrange(desc(sum_share)) %>% 
    left_join(actor, by = c("owned_id" = "id")) %>% 
    select(name, form, sum_share) %>% 
    as.data.frame()
# 91 and 95 are power plants, probably owned by two companies at the same - investigate further
# 98, 97, 101, 105, 104, 103, 99, 102 need to be further investigated
# #dummy data
# shareholder_relation <- data.frame(owner = c(1, 2, 3, 4), owned = c(4, 4, 5, 6), share = c(0.3, 0.7, 1, 1))
# shareholder <- data.frame(id = c(1, 2, 3, 4, 5, 6), name = c("Kanton Graubünden", "Gemeinde Zuoz", "Gemeinde S-chanf", "Axpo", "Alpiq", "KWO"), form = c("Kanton", "Gemeinde", "Gemeinde", "AG", "AG", "Kraftwerk"), power_output = c(rep(0,5), 4000))
# 
# shareholder_relation %>% write.csv("../shareholder_relation.csv", row.names = F)
# shareholder %>% write.csv("../shareholder.csv", row.names = F)

```



